BenedictWebApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace BenedictWebApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

BenedictWebApi/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using System.Linq;
using System.Web;

namespace BenedictWebApi.Models
{
    /// <summary>
    /// Model for the Booking
    /// </summary>
    public class Booking
    {
        public int Id { get; set; }

        [Display(Name = "Booking Name", Prompt = "Booking Name")]
        //This is mainly for the Client side validation
        [Required(ErrorMessage = "Please enter your name")]
        public string ClientName { get; set; }

        public DateTime ExpectedDate { get; set; }
        public int Duration { get; set; }
    }
}

BenedictWebApi/Models/BookingDb.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;


namespace BenedictWebApi.Models
{
    /// <summary>
    /// CodeFirst DbContext
    /// </summary>
    public class BookingDb : DbContext
    {
        public DbSet<Booking> Bookings { get; set; }


    }
}

BenedictWebApi/Models/BookingInitializer.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BenedictWebApi.Models
{
    /// <summary>
    /// CodeFirst Initializer for the BookingDb
    /// </summary>
    public class BookingInitializer : DropCreateDatabaseIfModelChanges<BookingDb>//DropCreateDatabaseAlways<BookingDb> //
    {
        protected override void Seed(BookingDb context)
        {
            base.Seed(context);

            //context.Bookings.Add(new Booking() { ExpectedDate = DateTime.Now, Duration = 30, ClientName = "Benedict" });

        }
    }
}

BenedictWebApi/Models/BookingRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BenedictWebApi.Models
{
    /// <summary>
    /// a Simple Booking Repository 
    /// </summary>
    public class BookingRepository : IBookingRepository
    {
        private BookingDb db = new BookingDb();

        public IEnumerable<Booking> GetAll()
        {
            return db.Bookings;
        }

        public Booking Get(int id)
        {
            return db.Bookings.FirstOrDefault(s => s.Id == id);
        }

        public Booking Add(Booking newBooking)
        {
            try
            {
                db.Bookings.Add(newBooking);
                db.SaveChanges();
                return newBooking;
            }
            catch
            {
                return null;
            }
        }

        public void Remove(int id)
        {
            var booking = db.Bookings.Find(id);
            db.Bookings.Remove(booking);
            db.SaveChanges();
        }
    }
}

BenedictWebApi/Models/IBookingRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BenedictWebApi.Models
{
    /// <summary>
    /// Interface for BookingRepository
    /// </summary>
    public interface IBookingRepository
    {
        IEnumerable<Booking> GetAll();
        Booking Get(int id);
        Booking Add(Booking newBooking);
        void Remove(int id);
    }
}

BenedictWebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using BenedictWebApi.Areas.HelpPage.Models;

namespace BenedictWebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

BenedictWebApi/Controllers/AdvertisementBookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using BenedictWebApi.Models;

namespace BenedictWebApi.Controllers
{
    /// <summary>
    /// The Web Api Controller, as requested only have one method to expose, others are commented at the moment
    /// </summary>
    public class AdvertisementBookingController : ApiController
    {
        private readonly IBookingRepository _repo;

        public AdvertisementBookingController(IBookingRepository repo)
        {
            this._repo = repo;
        }

        public IEnumerable<Booking> Get()
        {
            return this._repo.GetAll();
        }

        public Booking Get(int id)
        {
            return this._repo.Get(id);
        }

        public Booking Post(Booking item)
        {
            var newBooking = this._repo.Add(item);
            return newBooking;
        }

        public HttpResponseMessage Delete(int id)
        {
            this._repo.Remove(id);
            return new HttpResponseMessage(HttpStatusCode.NoContent);
        }
    }
}

BenedictWebApi/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BenedictWebApi.Controllers
{
    /// <summary>
    /// Just use as a simple MVC 4 page
    /// </summary>
    public class AdvertisementController : Controller
    {
        //
        // GET: /Advertisement/

        public ActionResult New()
        {
            return View();
        }

    }
}

BenedictWebApi/Views/Advertisement/New.cshtml
    <link href="~/Content/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" media="screen">


@model BenedictWebApi.Models.Booking

@{
    ViewBag.Title = "Tell the world, book your advertisement now";
}

@{ Html.EnableClientValidation(); }

<div class="content-wrapper">
    <div id="booking-div">



    @using (Html.BeginForm("New", "Advertisement", FormMethod.Post, new { id = "booking-form", @class = "form-horizontal" }))
{

    <fieldset>
        <legend>Book your Nine advertisement Now</legend>

        <div class="control-group">
            <label class="control-label" for="clientname">Company name</label>
            <div class="controls">
                @Html.EditorFor(model => model.ClientName, new { id="clientname" })
                @Html.ValidationMessageFor(model => model.ClientName)
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="expected-on">Advertising on </label>
            <div class="controls">

                <div class="input-append date datepicker" data-date="@DateTime.Today.AddDays(1).ToString("dd-MM-yyyy")" data-date-format="dd-mm-yyyy">
                    <input size="16" type="text" id="expected-on" value="@DateTime.Today.AddDays(1).ToString("dd-MM-yyyy")" readonly name="expectedon"><span class="add-on"><i class="icon-th"></i></span>
                </div>

                <div class="input-append bootstrap-timepicker">
                    <input id="expected-at" type="text" class="input-small">
                    <span class="add-on"><i class="icon-time"></i></span>
                </div>

            </div>



        </div>


        <div class="control-group">
            <label class="control-label" for="duration">Duration</label>
            <div class="controls">
                <select id="duration" name="duration">
                    <option value="15">15 seconds</option>
                    <option value="30">30 seconds</option>
                    <option value="45">45 seconds</option>
                    <option value="60"> 1 minute</option>
                </select>

            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <button id="submit" type="submit" class="btn btn-primary">Submit</button>
                <span class="field-validation-error" id="loading-span"><span for="">Loading.....</span></span>
            </div>
        </div>

    </fieldset>


    }
        </div>
</div>

<div class="content-wrapper">
    <div id="success-div">
    <form>
        <fieldset>
        <legend>Your advertisement has been booked</legend>

        <div class="controls controls-row">
            <label class="span2" for="s-clientname"><strong>Company name</strong></label>
            <label class="span3" id="s-clientname"></label>
        </div>
        <div class="controls controls-row">
            <label class="span2" for="s-expectedon"><strong>Advertising on</strong></label>
            <label class="span3" id="s-expectedon"></label>
        </div>
        <div class="controls controls-row">
            <label class="span2" for="s-duration"><strong>Duration</strong></label>
            <label class="span3" id="s-duration"></label>
        </div>

        <div class="control-group">
            <div class="controls">
                @Html.ActionLink("Book another one!", "New", null, new{@class="btn btn-primary"})
            </div>
        </div>

        </fieldset>
    </form>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/bootstrap-datepicker.js")
    @Scripts.Render("~/scripts/bootstrap-timepicker.min.js")
    @Scripts.Render("~/scripts/moment.min.js")





<script type="text/javascript">

         $(document).ready(new function () {
             $('.datepicker').datepicker({
                 format: 'dd-mm-yyyy',
                 startDate: moment().add('days', 1).toDate(),
                 todayHighlight: true
             });

             $('#expected-at').timepicker({
                 showMeridian: false,
                 minuteStep: 1
             });


             $('#submit').click(function () {

                 //This is to custom call the ASP.Net MVC DataAnnotations validation
                 var isValid = $('#booking-form').validate().form();
                 if (!isValid) return false;

                 //Create a forMap to help us get form data easily
                 var formMap = {};
                 $.each($('#booking-form').serializeArray(), function (i, o) {
                     formMap[o.name] = o.value;
                 });

                 //The data('datepicker') is found from the plugin-script of bootstrap-datepicker
                 //Which is used to get the datepicker object and allow us to call the inner function of getDate
                 var dateOn = $('#expected-on').parent().data('datepicker').getDate();

                 //Get the expected booking date from both the date and time picker
                 var expectedDate = new Date(dateOn.getFullYear(), dateOn.getMonth(), dateOn.getDate());
                 expectedDate.setHours(formMap.hour, formMap.minute, 0, 0);

                 //Prepare the duration
                 var duration = parseInt($('#duration').val());

                 //Prepare the data to post back to asp.net web api, note the date format, we use moment.js to help us format it
                 var postData = {}; 
                 postData['ExpectedDate'] = moment(expectedDate).format("YYYY-MM-DDTHH:mm:ss");
                 postData['Duration'] = duration;
                 postData['ClientName'] = formMap.ClientName;

                 //make the ajax post
                 $.ajax({
                     url: "../../api/advertisementbooking",
                     type: "POST",
                     data: JSON.stringify(postData),
                     contentType: 'application/json; charset=utf-8',
                     beforeSend: function () {
                         //Show loading text
                         $('#loading-span').toggle();
                     },
                     success: function (data) {
                         //Fill in the response data
                         $('#s-clientname').text(data.ClientName);
                         $('#s-expectedon').text(moment(data.ExpectedDate).format("DD-MM-YYYY HH:mm"));
                         $('#s-duration').text(data.Duration);
                         //Make some delay here just to show the effect
                         $('#booking-div').hide(2000);
                         $('#success-div').show(2000);
                     },
                     error: function (xhr, ajaxOptions, thrownError) {
                         //TO-DO, make this prettier
                         alert('Errors occurs, please try again later');
                     }
                 }).always(function () { $('#loading-span').hide(); });


                 return false;
             });

         });
</script> 

}

BenedictWebApi/Views/Home/Index.cshtml
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Welcome to ASP.NET Web API!</h1>
                <h2>Modify the code in this template to jump-start your ASP.NET Web API development.</h2>
            </hgroup>
            <p>
                ASP.NET Web API allows you to expose your applications, data and services to the
                web directly over HTTP.
            </p>
            <p>
                To learn more about ASP.NET Web API visit the
                <a href="http://go.microsoft.com/fwlink/?LinkID=238195" title="ASP.NET Web API Website">ASP.NET Web API Website</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET Web API.
                If you have any questions about ASP.NET Web API, visit
                <a href="http://go.microsoft.com/fwlink/?LinkID=238196" title="ASP.NET Web API Forum">our forums</a>.
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3>We suggest the following steps:</h3>
        <ol class="round">
            <li class="one">
                <h5>Getting Started</h5>
                ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
                a broad range of clients, including browsers and mobile devices. ASP.NET Web API
                is an ideal platform for building RESTful applications on the .NET Framework.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245160">Learn more…</a>
            </li>

            <li class="two">
                <h5>Add NuGet packages and jump-start your coding</h5>
                NuGet makes it easy to install and update free libraries and tools.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245161">Learn more…</a>
            </li>
            <li class="three">
                <h5>Find Web Hosting</h5>
                You can easily find a web hosting company that offers the right mix of features
                and price for your applications.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245164">Learn more…</a>
            </li>
        </ol>
    </section>
</div>

BenedictWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" media="screen">

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper clearfix">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">Benedict's Exercise</a></p>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/scripts/bootstrap.min.js")

    @RenderSection("scripts", required: false)
</body>
</html>